CREATE TABLE [ERP].[dbo].[EXPORT] (
    RowID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
    TransactionId NVARCHAR(50) NOT NULL,
    Status NVARCHAR(50) DEFAULT 'Posted',
    State NVARCHAR(50) NOT NULL,
    PartNumber NVARCHAR(50) NOT NULL,
    PartRevision NVARCHAR(6) NOT NULL,
    NewPartRevision NVARCHAR(50) NULL,
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    InternalDescription NVARCHAR(MAX) NULL,
    Quantity NVARCHAR(50) NULL,
    Units NVARCHAR(50) NOT NULL,
    Position NVARCHAR(50) NULL,
    Children [nvarchar](6) NULL,
    ParentPartNumber NVARCHAR(50) NULL,
    ParentPartRevision [nvarchar](6) NULL,
    Category NVARCHAR(50) NOT NULL,
    Mass NVARCHAR(100) NULL,
    Material NVARCHAR(50) NULL,
    Certificate NVARCHAR(50) NULL,
    SerialNumber NVARCHAR(50) NULL,
    Spare NVARCHAR(6) DEFAULT 'NO',
    Critical NVARCHAR(6) DEFAULT 'NO',
    LongLead NVARCHAR(6) DEFAULT 'NO',
    Supplier NVARCHAR(50) NULL,
    SupplierPartNumber NVARCHAR(50) NULL,
    Author NVARCHAR(100) NOT NULL
    Released DATETIME DEFAULT GETDATE() NOT NULL,
    Updated DATETIME DEFAULT GETDATE() NULL
);