import { v4 as uuid } from "uuid";

export const get_fields = () : Fields  => ({
    "rowID": "NEWID()",
    "ItemNumber": "NULL",
    "Revision": "NULL",
    "Quantity": "NULL",
    "Pos": "NULL",
    "ParentItemNumber": "NULL",
    "ParentItemRevision": "NULL",
    "ChildCount": "'0'",
    "Category": "NULL",
    "Title": "NULL",
    "Description": "NULL",
    "Units": "'Each'",
    "LifecycleState": "'Work in Progress'",
    "Category_1": "NULL",
    "Category_2": "NULL",
    "Category_3": "NULL",
    "Category_4": "NULL",
    "InternalDescription": "NULL",
    "Mass_g": "NULL",
    "Material": "NULL",
    "MaterialCertifikate": "NULL",
    "Project": "NULL",
    "SerialNo": "NULL",
    "SparePart": "NULL",
    "Vendor": "NULL",
    "CriticalItem": "NULL",
    "LongLeadItem": "NULL",
    "SupplierPartNo": "NULL",
    "ReleaseDate": "CONVERT(VARCHAR, GETDATE(), 127) + 'Z'",
    "LastUpdate": "CONVERT(VARCHAR, GETDATE(), 127) + 'Z'",
    "Status": "'Posted'",
    "ErrorDescription": "NULL",
    "ReleasedBy": "NULL",
    "LastUpdatedBy": "NULL",
    "State(Historical)": "'Work in Progress'",
    "TransactionId": `'${uuid()}'`,
    "InventorQuantity": "NULL",
    "NewRevision": "NULL",
    "NewParentItemRevision": "NULL"
  });

  export type Fields = {
    "rowID": string,
    "ItemNumber": string,
    "Revision": string,
    "Quantity": string,
    "Pos": string,
    "ParentItemNumber": string,
    "ParentItemRevision": string,
    "ChildCount": string,
    "Category": string,
    "Title": string,
    "Description": string,
    "Units": string,
    "LifecycleState": string,
    "Category_1": string,
    "Category_2": string,
    "Category_3": string,
    "Category_4": string,
    "InternalDescription": string,
    "Mass_g": string,
    "Material": string,
    "MaterialCertifikate": string,
    "Project": string,
    "SerialNo": string,
    "SparePart": string,
    "Vendor": string,
    "CriticalItem": string,
    "LongLeadItem": string,
    "SupplierPartNo": string,
    "ReleaseDate": string,
    "LastUpdate": string,
    "Status": string,
    "ErrorDescription": string,
    "ReleasedBy": string,
    "LastUpdatedBy": string,
    "State(Historical)": string,
    "TransactionId": string,
    "InventorQuantity": string,
    "NewRevision": string,
    "NewParentItemRevision": string
  };

  export type BOM = Pick<Fields, "ItemNumber" | "Revision" | "Category" | "Title" | "Description" | "LifecycleState" | "Mass_g" | "Vendor" | "SupplierPartNo" | "ReleasedBy" | "LastUpdatedBy" | "State(Historical)" >
  export type Part = Pick<Fields, "ItemNumber" | "Quantity" | "Pos" | "ParentItemNumber" | "ParentItemRevision" | "Revision" | "Category" | "Title" | "Description" | "LifecycleState" | "Mass_g" | "Vendor" | "SupplierPartNo" | "ReleasedBy" | "LastUpdatedBy" | "State(Historical)" | "InventorQuantity">