export type PartInventory = {
  "Part No": string;
  "Part Description in Use": string;
  "Part Description": string;
  Site: string;
  "Site Description": string;
  "Part Type": string;
  Planner: string;
  "Inventory UoM": string;
  "Catch UoM": string;
  "Input UoM Group": string;
  "Commodity Group 1": string;
  "Commodity Group 2": string;
  "Asset Class": string;
  "Asset Class Description": string;
  "Part Status": string;
  "Part Status Description": string;
  "ABC Class": string;
  "Frequency Class": string;
  "Lifecycle Stage": string;
  "Safety Code": string;
  "Accounting Group": string;
  "Accounting Group Description": string;
  "Product Code": string;
  "Product Code Description": string;
  "Product Family": string;
  "Product Family Description": string;
  "Type Designation": string;
  "Dimension/Quality": string;
  "Net Weight": string;
  "Weight UoM": string;
  "Net Volume": string;
  "Volume UoM": string;
  "On Hand Qty": string;
  "On Hand Catch Qty": string;
  Created: string;
  Modified: string;
  "Document Text": string;
  Notes: string;
  "Lead Time Code": string;
  "Purchasing Lead Time": string;
  "Earliest Unlimited Supply Date": string;
  "Manufacturing Lead Time": string;
  "Expected Lead Time": string;
  "Supersedes Part": string;
  "Superseded By Part": string;
  "Shelf Life in Days": string;
  "Minimum Remaining Days at CO Delivery": string;
  "Minimum Remaining Days for Planning": string;
  "Country of Origin": string;
  "Region Code": string;
  "Customs Statistics No": string;
  "Customs Stat Desc": string;
  "Intrastat Conv Factor": string;
  "Customs UoM": string;
  "Supply Chain Part Group": string;
  "Supply Chain Part Group Description": string;
  "Default Mtrl Req Supply": string;
  "DOP Connection": string;
  "DOP Netting": string;
  "Tech Coordinator": string;
  "Qty Calc Rounding": string;
  Configurable: string;
  "Inventory Valuation Method": string;
  "Inventory Part Cost Level": string;
  "Supplier Invoice Consideration": string;
  "Zero Cost": string;
  "Part Cost Group ID": string;
  "Part Cost Group Description": string;
  "External Service Cost Method": string;
  "Cycle Counting Interval": string;
  "Cum Count Diff": string;
  "Cycle Counting": string;
  "Reserve at order entry": string;
  "Automatic Capability Check": string;
  "Negative On Hand": string;
  "Availability Check": string;
  "Availability Check at CO Reserve": string;
  "Online Consumption": string;
  "Shortage Notification": string;
  "Stock Management": string;
  "Refill Putaway Zones": string;
  "Refill Putaway Zones Operative Value": string;
  "Refill Putaway Zones Source": string;
  "Std Putaway Qty": string;
  "Pallet Handled": string;
  "Inventory Part Standard Name ID": string;
  "Inventory Part Standard Name": string;
  "Part Catalog Standard Name ID": string;
  "Part Catalog Standard Name": string;
  GTIN: string;
  "GTIN Series": string;
  "Alternate Parts Exist": string;
  "Characteristic Template": string;
  "Storage Width Requirement": string;
  "Operative Storage Width Requirement": string;
  "Storage Width Requirement Source": string;
  "Storage Height Requirement": string;
  "Operative Storage Height Requirement": string;
  "Storage Height Requirement Source": string;
  "Storage Depth Requirement": string;
  "Operative Storage Depth Requirement": string;
  "Storage Depth Requirement Source": string;
  "UoM for Length": string;
  "Qty per Volume": string;
  "Operative Qty per Volume": string;
  "Qty per Volume Source": string;
  "UoM for Volume": string;
  "Storage Weight Requirement": string;
  "Operative Storage Weight Requirement": string;
  "Storage Weight Requirement Source": string;
  "UoM for Weight": string;
  "Min Storage Temperature": string;
  "Operative Min Storage Temperature": string;
  "Min Storage Temperature Source": string;
  "Max Storage Temperature": string;
  "Operative Max Storage Temperature": string;
  "Max Storage Temperature Source": string;
  "UoM for Temperature": string;
  "Min Storage Humidity (%)": string;
  "Operative Min Storage Humidity (%)": string;
  "Min Storage Humidity (%) Source": string;
  "Max Storage Humidity (%)": string;
  "Operative Max Storage Humidity (%)": string;
  "Max Storage Humidity (%) Source": string;
  "Subject to Overheads": string;
  "SCT Taxable": string;
};

export type PartEngineering = {
  "Part Number": string;
  "Std Name ID": string;
  "Standard Name": string;
  "Language Standard Name": string;
  "Current Revision": string;
  "Part Description": string;
  "Part Description in Selected Language": string;
  "Part Class": string;
  "Part Class Description": string;
  "Technical Class	Doc. Req. ID": string;
  "Project Doc. Req. ID": string;
  "Part Main Group": string;
  "Part Main Group Description": string;
  UoM: string;
  "UoM Description": string;
  "Last Revision No": string;
  "Last Revision": string;
  "Provide Code": string;
  "MPL Part": string;
  "Planning Method": string;
  Configurable: string;
  "Lot/Batch Tracking": string;
  "After Delivery Serial Tracking": string;
  "Inventory Serial Tracking": string;
  "Revision Number Maximum": string;
  "Revision Number Approved": string;
  "Responsible ID": string;
  Responsible: string;
  Modified: string;
  "Modified By": string;
  Created: string;
  "Created By": string;
};

export type PartEngineeringRevision = {
  "Part Number": string;
  "Eng Rev": string;
  "Revision Number": string;
  "Standard Name": string;
  "Language Standard Name": string;
  "Engineering Part Description": string;
  "Part Description in Selected Language": string;
  Status: string;
  Released: string;
  Obsoleted: string;
  Activated: string;
  "Development Level Description": string;
  "Has Spare Parts": string;
  "CO No": string;
  "Approval Template": string;
  Note: string;
  "Actual Lead Time": string;
  "Assumed Lead Time": string;
  "Assumed Cost": string;
  "Calculated Cost": string;
  "Calculated Work Cost": string;
  "Calculated Work Hours": string;
  "Material Cost": string;
  "Work Cost": string;
  "Work Hours": string;
  "Standard Cost": string;
  "Average Purch Price": string;
  "Last Purchase Price": string;
  "Stop Report": string;
  "Transferred To Manufacturing": string;
  Modified: string;
  "Modified By": string;
  Created: string;
  "Created By": string;
};

export type PartPurchase = {
  "Part No": string;
  "Part Description": string;
  "Purchase Part Description": string;
  Site: string;
  "Site Desc": string;
  "Alternate Parts Exist": string;
  Created: string;
  "Default Purch UoM": string;
  "UoM Desc": string;
  Taxable: string;
  "Quality Approval Date": string;
  "QC Analyst ID": string;
  "Inventory Part": string;
  Contractor: string;
  "Dim/Quality": string;
  "Buyer ID": string;
  "Buyer Name": string;
  "Tech Coordinator": string;
  "Acquisition Type": string;
  "Purchase Group": string;
  "Purchase Group Desc": string;
  "Order Proc Type": string;
  "Order Proc Type Desc": string;
  "Closing Code": string;
  "Closing Tolerance (%)": string;
  "Over Delivery Check": string;
  "Over Tolerance (%)": string;
  "Type Designation": string;
  Note: string;
  "Document Text": string;
  "Characteristic Template": string;
};

export type PartSale = {
  "Sales Part No": string;
  "Part Description in Use": string;
  "Sales Part Description": string;
  Site: string;
  "Type Of Sales Part": string;
  "Sales Group": string;
  "Sales Price Group": string;
  "Rebate Group": string;
  "Part No": string;
  Description: string;
  "Inventory UoM": string;
  Configurable: string;
  DOP: string;
  "Purchase Part": string;
  "Sourcing Option": string;
  "Sourcing Rule": string;
  "Rule Description": string;
  "Sales UoM": string;
  "Conversion Factor": string;
  "Inverted Conversion Factor": string;
  "Price UoM": string;
  "Price Conversion Factor": string;
  Price: string;
  "Rental Price": string;
  "Exp Avg Price": string;
  "Min Sales Qty": string;
  "Discount Group": string;
  "Tax Code": string;
  "Tax Class": string;
  "Closing Tolerance (%)": string;
  "Use Price Incl Tax": string;
  Taxable: string;
  "Primary Sales Part": string;
  "Active Part": string;
  "Export to External Application": string;
  "Rental Price Incl Tax": string;
  "Price incl Tax": string;
  "Base Curr": string;
  Created: string;
  "Quickly Registered Part": string;
  GTIN: string;
  "Delivery Type": string;
  "Price Modified": string;
  "Net Weight": string;
  "Weight UoM": string;
  Volume: string;
  "Volume UoM": string;
  "Freight Factor": string;
  "Characteristic Template": string;
  "Print Code": string;
  Cost: string;
  Notes: string;
  "Customer Warranty": string;
  "Create SM Object": string;
  "Replacement Part No": string;
  "Replacement Date": string;
  Category: string;
  "Customs Stat No": string;
  "Intrastat Conv Factor": string;
  "Document Text": string;
  "Sales Type": string;
};
